services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus-config:/etc/prometheus
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    networks:
      - public-overlay
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  loki:
    image: grafana/loki:3.0.0
    configs:
      - source: loki_config
        target: /etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - public-overlay
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  tempo:
    image: grafana/tempo:latest
    configs:
      - source: tempo_config
        target: /etc/tempo/tempo.yaml
    command: -config.file=/etc/tempo/tempo.yaml
    networks:
      - public-overlay
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    configs:
      - source: promtail_config
        target: /etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - public-overlay
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  node_exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
    networks:
      - public-overlay
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SERVER_ROOT_URL=https://192.168.122.138/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-data:/var/lib/grafana
    configs:
      - source: grafana_datasources
        target: /etc/grafana/provisioning/datasources/datasources.yaml
      - source: grafana_dashboard_provider
        target: /etc/grafana/provisioning/dashboards/dashboards.yaml
      - source: grafana_dashboard_homelab
        target: /etc/grafana/provisioning/dashboards/homelab-dashboard.json
    networks:
      - public-overlay
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=PathPrefix(`/grafana`)"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.routers.grafana.tls=true"
        - "traefik.http.routers.grafana.service=grafana"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      restart_policy:
        condition: on-failure

configs:
  prometheus_config:
    file: ./prometheus.yml
  loki_config:
    file: ./loki-config.yml
  tempo_config:
    file: ./tempo-config.yml
  promtail_config:
    file: ./promtail-config.yml
  grafana_datasources:
    file: ./grafana-provisioning/datasources/datasources.yaml
  grafana_dashboard_provider:
    file: ./grafana-provisioning/dashboards/dashboards.yaml
  grafana_dashboard_homelab:
    file: ./grafana-provisioning/dashboards/homelab-dashboard.json

volumes:
  prometheus-config:
  grafana-data:

networks:
  public-overlay:
    external: true
