---
- name: Deploy Application Stack on Manager Node
  block:
    - name: Ensure applications directory exists
      ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/applications"
        state: directory
        mode: '0755'

    - name: Copy app-stack.yml template
      ansible.builtin.template:
        src: app-stack.yml.j2
        dest: "{{ ansible_facts['user_dir'] }}/applications/app-stack.yml"
        mode: '0644'

    - name: Deploy Application Stack
      ansible.builtin.command: docker stack deploy -c "{{ ansible_facts['user_dir'] }}/applications/app-stack.yml" app
  when: inventory_hostname in groups['managers']
